version: '3'
services:
  api01: &api
    build: .
    hostname: api01
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://localhost:27017/rinha
      - PORT=5666
    network_mode: host

  api02:
    <<: *api
    environment:
      - MONGO_URI=mongodb://localhost:27017/rinha
      - PORT=5667
    hostname: api02

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    network_mode: host

  mongo:
    image: mongo
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    ports:
      - "27017:27017"
    network_mode: host
