version: '3'
services:
  app:
    build: .
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://localhost:27017
      - PORT=5666
    network_mode: host
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    network_mode: host